name: 'Analyze .map file with Amap'

on:
  push:
    branches:
      - dev
      - "release*"
    tags:
      - '*'
  pull_request:

env:
  TARGETS: f7

jobs:
  amap_analyse:
    runs-on: [self-hosted,FlipperZeroMacShell]
    steps:
      - name: 'Decontaminate previous build leftovers'
        run: |
          if [ -d .git ]
          then
            git submodule status \
              || git checkout `git rev-list --max-parents=0 HEAD | tail -n 1`
          fi

      - name: 'Checkout code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Build the firmware'
        run: SET_GH_OUTPUT=1 FBT_TOOLCHAIN_PATH=/opt ./fbt

      - name: 'Make artifacts directory'
        run: |
          rm -rf artifacts
          mkdir artifacts

      - name: 'Make amap report'
        run: |
          cp build/latest/firmware.elf.map artifacts/
          cd artifacts/
          /Applications/amap/Contents/MacOS/amap -f firmware.elf.map

      - name: 'Generate suffix'
        id: names
        run: |
          REF=${{ github.ref }}
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            REF=${{ github.head_ref }}
          fi
          BRANCH_OR_TAG=${REF#refs/*/}
          SHA=$(git rev-parse --short HEAD)

          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            SUFFIX=${BRANCH_OR_TAG//\//_}
          else
            SUFFIX=${BRANCH_OR_TAG//\//_}-$(date +'%d%m%Y')-${SHA}
          fi

          echo "::set-output name=suffix::${SUFFIX}"

      - name: 'Upload report to database'
        run: |
          /usr/local/bin/amap_mariadb_insert.py firmware.elf.map.all {{steps.names.outputs.suffix}}
