name: 'Analyze .map file with Amap'

on:
  push:
    branches:
      - dev
      - "release*"
    tags:
      - '*'
  pull_request:

env:
  TARGETS: f7

jobs:
  lint_c_cpp:
    runs-on: [self-hosted,FlipperZeroMacShell]
    steps:
      - name: 'Decontaminate previous build leftovers'
        run: |
          if [ -d .git ]
          then
            git submodule status \
              || git checkout `git rev-list --max-parents=0 HEAD | tail -n 1`
          fi

      - name: 'Checkout code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Build the firmware'
        run: SET_GH_OUTPUT=1 FBT_TOOLCHAIN_PATH=/opt ./fbt

